language: C

compiler: gcc

# whitelist
branches:
  only:
  - master
  - development

before_install:
- brew update
- brew install pyenv
- eval "$(pyenv init -)"
- pyenv install 2.7.6
- pyenv global 2.7.6
- pyenv rehash
- pip install cpp-coveralls
- pyenv rehash

script: 
- make
- cd ./tests
- python run_all.py

after_success:
- coveralls --exclude tests --exlude examples --gcov-options '\-lp'
